version: "3.8"

services:
  db-carrinho-de-compras:
    image: postgres:16.2
    hostname: db
    container_name: "containerBancoDeDadosCarrinhoDeCompras"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./../scriptBancoDeDados:/docker-entrypoint-initdb.d
    ports:
      - "5435:5432"
    restart: always